<a href="https://colab.research.google.com/github/Alamgir-JUST/Machine-Learning-Projects/blob/main/Employee_Churn_Prediction_using_Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Complete Coding with Naive Bayes**

In [4]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [5]:
# Load the training and testing datasets
df = pd.read_csv('/content/drive/MyDrive/Machine Learning Lab/employee_churn_dataset.csv')

In [6]:
df

,Age,Gender,Income,MaritalStatus,Education,Employment,WorkExperience,Location,HealthStatus,Churn
0,50-60,Female,Low,Divorced,PhD,Employed,0,Urban,Good,1
1,>60,Female,High,Married,High School,Employed,38,Urban,Good,0
2,40-50,Female,High,Married,PhD,Unemployed,31,Suburban,Excellent,1
3,>60,Male,Low,Divorced,Bachelor,Employed,28,Rural,Average,1
4,>60,Male,Medium,Single,PhD,Unemployed,16,Rural,Average,0
...,...,...,...,...,...,...,...,...,...,...
99995,30-40,Male,Medium,Married,Bachelor,Employed,19,Rural,Average,1
99996,<30,Male,High,Married,PhD,Unemployed,22,Suburban,Excellent,0
99997,>60,Female,High,Single,High School,Unemployed,12,Urban,Good,0
99998,50-60,Male,Low,Single,High School,Employed,30,Suburban,Excellent,1
99999,<30,Male,High,Divorced,Master,Employed,4,Urban,Excellent,1

In [7]:
df.value_counts("Churn")

Churn
0    50215
1    49785
Name: count, dtype: int64

In [8]:
# Importing necessary libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

# Step 1: Data Preprocessing
# Encoding categorical features using LabelEncoder
label_encoder = LabelEncoder()

# Apply LabelEncoder to each feature
data_encoded = df.copy()
for column in data_encoded.columns:
    data_encoded[column] = label_encoder.fit_transform(data_encoded[column])

# Step 2: Splitting data into features (X) and target (y)
X = data_encoded.drop('Churn', axis=1)
y = data_encoded['Churn']

# Step 3: Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Step 4: Train Naive Bayes model
nb_classifier = GaussianNB()
nb_classifier.fit(X_train, y_train)

# Step 5: Make predictions on the test set
y_pred = nb_classifier.predict(X_test)

# Step 6: Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

# Display results
print(f'Accuracy: {accuracy * 100:.2f}%')
print('Classification Report:')
print(report)

Accuracy: 49.94%
Classification Report:
              precision    recall  f1-score   support

           0       0.50      0.74      0.60     14957
           1       0.50      0.26      0.34     15043

    accuracy                           0.50     30000
   macro avg       0.50      0.50      0.47     30000
weighted avg       0.50      0.50      0.47     30000

# **Thank You**